### ISSUE TITLE
Monitor the NixOS Version of deployed instances

### ISSUE THREAD

**Issue by alastairong** [Holo-Host/bugs-n-issues#41]
HoloPorts auto-update from hydra channel every 10 minutes. This is fine for the majority of users but does occasionally get stuck. The update is silent so we have no idea what causes the issues, only that we occasionally are able to resolve problems by manually forcing updates or reboots.

I would guess that issues affect ~1% of HPs, which is still too much given the importance of the update.

I don't know that there's a single root cause to fix, or that new root causes will not surface in future. So my question is:

"What can we do to make the auto-update process more resilient, so that given a 10 minute update check, all HoloPorts will be updated within 24 hours". I.e. permanent blockages are always eventually resolved."

**Comment by grahamc** [comment]
Would it be possible to get us onto a machine experiencing this problem?

**Comment by alastairong** [comment]
If you get your SSH keys added to the profiles.development list then you'll have access. The issue is usually we don't know it's encountering it until after we manually update it and it starts downloading files from a channel it should already be updated to.

**Comment by alastairong** [comment]
I like the proposal you discussed with PJ to start collecting data on the current holo-nixpkgs revision hash :)

**Comment by peeech** [comment]
An action item here is: adding a property which represents a state of HPOS (hash?, git revision?) to properties collected by netstatsd, which in turn will allow us to run analytics and discover delays in system update on holoports.

**Comment by alastairong** [comment]
@peeech Will add to backlog

**Comment by alastairong** [comment]
@grahamc After discussing this with @peeech, what we need from you is advice on what property we should be using for the build "version" a HoloPort is currently updated to, and how to get it. 

In the past I think we've looked at using the git revision or the build #, but we get both via `curl` to hydra separately to updating, so there's a risk that it doesn't reflect what is actually running if we get stuck updating.

We're also aware of the sha in the `manifest.nix`  but again, not sure if this is the best option or how to check what the correct sha should be.
 
Is this something you can look into?

**Comment by cole-h** [comment]
We're playing around with a few ideas in https://github.com/Holo-Host/holo-nixpkgs/pull/1205.

**Comment by alastairong** [comment]
Yes that is fine

**Comment by firestack** [comment]
I've opened a few PR's, But 
- https://github.com/Holo-Host/holo-nixpkgs/pull/1205
- https://github.com/Holo-Host/net-stats-daemon/pull/6 (Cannot add reviewers )
- https://github.com/Holo-Host/hp-stats-api/pull/19 ( Cannot add reviewers ) 
Of which there are two PR's, listed above, on which I cannot add reviewers.

I think are enough to solve #41 but I need feedback in case there's something I'm missing, I'm also concerned there's more code that I'm unable to find that I also need to change. It is also unclear where the source for https://network-statistics.holo.host/holoports/ lives and if it can automatically handle more data being added to the entries in MongoDB.

On top of this, I don't have a very easy way to build and test these changes (Due to nix expressions for these repositories being located elsewhere), I'd appreciate and welcome any guidance on how to go about building and testing these PR's.
